name: Test Colab Badge Action
on: [push, pull_request]

jobs:
  build:
    name: Colab Badge Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v3.1
        with:
          args: ''
          check: 'all'
          update: true
          target_branch: main
          target_repository: trsvchn/colab-badge-action-demo

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add/Update Colab badges"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
